name: Deploy React to EC2 with Nginx

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm install

    - name: Build the React app
      run: |
        npm run build

    - name: Deploy to EC2
      env:
        EC2_KEY_PATH: ${{ secrets.EC2_SSH_KEY }}
        EC2_HOST: ${{ secrets.HOST_DNS }}
        EC2_USER: ${{ secrets.USERNAME }}
      run: |
        # Create build folder path to deploy the build
        BUILD_PATH="./build/*"

        # Sync the build to EC2 using scp
        scp -i $EC2_KEY_PATH -o StrictHostKeyChecking=no -r $BUILD_PATH $EC2_USER@$EC2_HOST:/home/ubuntu/drrajivbhushan-portfolio/

        # SSH into EC2 and restart Nginx
        ssh -i $EC2_KEY_PATH -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
          sudo systemctl restart nginx  # Restart Nginx to load the new build
        EOF

    - name: Notify Deployment Success
      run: echo "React app has been successfully deployed to EC2!"
